### ISSUE TITLE
Botões de Estado 1, 2, 3, 4 funcionando com Touch Out apenas

### ISSUE THREAD

**Issue by filipecalegario** [nataliacabral/ControladorDinamico#14]
Os Botões de Estado do Play Mode só estão setando o estado quando o dedo é removido do botão. Como isso adiciona um atraso na interação, é preciso que o estado seja trocado assim que o dedo do usuário apertar o botão. Em vez de Touch Out, o evento precisa ser Touch In.

**Comment by nataliacabral** [comment]
Calega, fiquei com uma dúvida aqui. Quando tu diz que o evento é para ser salvo no touch in, tu quer dizer que não precisa ser mais um long touch? Ou seja, assim que o usuário clicar (como um botão normal), ele ja salva o estado. É isso?

**Comment by filipecalegario** [comment]
opa natália,

não não, o long press continua e está funcionando muito bem.
o que eu tô dizendo do touch in é assim que o botão for tocado ele aciona
as ações associadas a ele.
o que está funcionando agora é que as ações só estão sendo disparadas
quando eu tiro o dedo do botão, ou seja, touch out.

abração!

Filipe Calegario
filipecalegario.net

2015-04-07 20:34 GMT-04:00 nataliacabral notifications@github.com:
